### ISSUE TITLE
How to use "page[size]" parameter?

### ISSUE THREAD

**Issue by hhissami** [klaviyo/klaviyo-api-python#12]
Hi!

I am trying to get Segment Profiles with:

`klaviyo.Segments.get_segment_profiles(segment_id, fields_profile=fields_profile, filter=filter, page_cursor=page_cursor)
`

Is it possible to specify how many results I want to be returned with the **page[size]** parameter?

Thanks!

**Comment by jon-batscha** [comment]
Hey! Thanks for reaching out again!

We just shipped an update, so if you check out [this section](https://github.com/klaviyo/klaviyo-api-python#get-segment-profiles) of the README, you'll see that we now support this as a `kwarg`.

As you can see in our updated [API docs](https://developers.klaviyo.com/en/reference/get_segment_profiles), our default/max values for this are as follows:

- default: 20
- max: 100
