### ISSUE TITLE
No Page Size in "get_profiles"

### ISSUE THREAD

**Issue by defyned-matt** [klaviyo/klaviyo-api-python#16]
Looks like pages size is not implemented per docs:

## Keyword Arguments

# fields_profile | [str]
# filter | str
# page_cursor | str
# sort | str
# page_size | int

klaviyo.Profiles.get_profiles(fields_profile=fields_profile, filter=filter, page_cursor=page_cursor, sort=sort, **page_size=page_size**)

**Comment by jon-batscha** [comment]
Hey! 

Apologies for the delay, `page_size` is implemented, it's just listed last in the list of keyword args, so you may have missed it visually. That said, you're prob not the only wondering where this param is, so i'll make a ticket for us to get these params back in alphabetical order.


Cheers,
Jon
