### ISSUE TITLE
Rendering templates

### ISSUE THREAD

**Issue by dsoprea** [klaviyo/klaviyo-api-python#20]
We'd like to use templates from Klaviyo to send some emails ourselves. We can get the templates via the API and, of course, it'd be inefficient to call the API for every single email we want to send. We would rather avoid implementing the parsing ourselves. However, it doesn't seem as if this provides any rendering ability even if wholly manual (because none of the profile properties and/or other macros available in the UI would be present/available in this context). Thoughts/suggestions? Is this a standard templating engine/dialect that I can use from Python to render?

**Comment by jon-batscha** [comment]
Hey, great question!

As you alluded to, we have a [render_template](https://developers.klaviyo.com/en/reference/create_template_render) endpoint, though as you alluded to, the rate limit is sufficiently low such that it’s available for testing as opposed to running production workloads.

As for whether you can overcome this rate limit by rendering the email yourself before sending it on your own: yes, though with some caveats.
 Klaviyo uses [the Django Template Language](https://docs.djangoproject.com/en/4.2/ref/templates/api/#django.template.Context), though with some customizations. If your template uses standard Django (e.g: just context variables), you should be able to render it using something like the following: 
```python 
from django import template
from django.template import Context, Template
from django.conf import settings
import django
import json
import datetime

template_file = 'template.html'
context_file = 'context.json'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
    },
]

settings.configure(TEMPLATES=TEMPLATES)
django.setup()

register = template.Library()

@register.simple_tag
def current_year():
    return datetime.datetime.now().year

with open(template_file, 'r') as f:
    template_text = '{% load current_year %}' + f.read()

with open(context_file, 'r') as f:
    context_payload = json.load(f)
    
template = Template(template_text)
context = Context(context_payload)
rendered = template.render(context)

with open('rendered.html', 'w') as f:
    f.write(rendered)
```

Caveat: If your template uses non-standard Django features (e.g: Klaviyo-specific tags, such as `{% current_year  %}`), you may need to make some modifications (such as above code for registering `current_year` as a tag and adding `{% load current_year %}` to start of template). We might be using a common extension of the Django template language, though I'll need to look into that. I'll also look into whether there is additional tooling/code samples we can share to cover more cases, maybe a django app that defines all tags.

In the meantime, I’ll link you these 2 guides which you may find helpful. 
- https://developers.klaviyo.com/en/docs/django_message_design
- https://help.klaviyo.com/hc/en-us/articles/4408802648731


Please reach out if you run into any further issues, we really value this kind of feedback.


Cheers,
Jon
