### ISSUE TITLE
permissions issue with getting lists + campaign audience type (List\Segment)

### ISSUE THREAD

**Issue by odedva** [klaviyo/klaviyo-api-python#26]
Hi there,
we use the API to read the profiles of a specific campaign. in order to achieve that we take the audience object and for each `includes` id we fetch the profiles via the list api. i have 2 questions:
1. we don't know if the id of the audience is of type List OR Segment - is there a straight forward way to understand that? for now we try to get profiles as List and if we get 404 we try as Segment.
2. when using the sdk for `Lists.get_list(id)` - we have a permission problem (we get 403 response)as it requires list:write (although `Lists.get_lists()`) work with the same token) - is this a bug or are we missing something?
thanks for the help!

**Comment by vpylypenko-klaviyo** [comment]
Oded, thanks for reporting the issues. 

1. Currently, there is no way to differentiate lists from segments used to define the audience. The approach you described should work for now - make a call to `/api/lists/{list_id}/profiles`, if response status code is `404`, make a call to `/api/segments/{segment_id}/profiles`.
2. I've filed a ticket with a development team and the issue will be addressed within a few days. `/api/lists/{list_id}` will have `list:read` scope.
