### ISSUE TITLE
klaviyo.Templates.get_template return error 500

### ISSUE THREAD

**Issue by davhin** [klaviyo/klaviyo-api-python#27]
Hey all,

relatively recently (yesterday?) I started receiving error 500 when trying to get a single template with the Templates.get_template endpoint. It seems like the .get_templates is still working so I can access the templates that way. I am using 3.0.0 of the klaviyo api

If it helps here is the exception:
`ServiceException: Status Code: 500
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 27 Jun 2023 14:01:23 GMT', 'Content-Type': 'application/vnd.api+json', 'Content-Length': '234', 'Connection': 'keep-alive', 'CF-Ray': '7dde38bf69c2b734-AMS', 'CF-Cache-Status': 'DYNAMIC', 'Allow': 'GET, PUT, PATCH, DELETE, HEAD, OPTIONS', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'Vary': 'Cookie, Accept-Encoding', 'CID': 'UeZz4r', 'Content-Security-Policy-Report-Only': "base-uri 'none'; script-src 'strict-dynamic' 'unsafe-eval'; frame-ancestors 'self'; object-src 'none'", 'RateLimit-Limit': '150, 10;w=1, 150;w=60', 'RateLimit-Remaining': '149', 'RateLimit-Reset': '22', 'X-Content-Type-Options': 'nosniff', 'X-Klaviyo-API-Revision': '2022-10-17', 'X-Robots-Tag': 'noindex, nofollow', 'Server': 'cloudflare'})
HTTP response body: {"errors":[{"id":"a73df42f-251d-4bf3-99bb-841fa26c2446","status":500,"code":"error","title":"A server error occurred.","detail":"While structuring TemplateResponseDeprecated (1 sub-exception)","source":{"pointer":"/data"},"meta":{}}]}`

Best,
David

**Comment by davhin** [comment]
I also found that when I use Templates.get_templates() I get fewer templates than what Campaigns.get_campaign_message() and using the contained 'template_id' would impy. Does the Campaigns API include potentially deleted templates and the Templates API does not?

Happy for any insight!

**Comment by jon-batscha** [comment]
Hey, thanks for reaching out!


Regarding the 500 error: I was able to reproduce the issue on my end. The team that owns this is looking into it now.

Regarding your second question:

The reason for this is that we essentially have 2 types of templates: reusable templates and non-reusable templates.

Reusable templates are what you edit; when a campaign message gets assigned a template, that template is actually a non-reusable clone of the given template.

`get_templates` only returns the original, reusable templates, hence the count mismatch.

That said, this overall behavior is as puzzling to me as it is to you, as presumably we’d want some way to trace a given non-reusable template back to its source, which is not currently possible. This also seems to be related to the 500 errors we’re seeing, as I’m only seeing the error when calling `get_template` on a non-reusable template’s id.

I know that ’s not the optimal answer you were looking for, as we clearly have some work to do to improve these endpoints. While we're waiting on this fix, I’ll also reach out to our writing team to put together a guide to clarify reusable vs non-reusable templates.

Please do reach out if you run into any further issues. We super appreciate this kind of feedback, as it helps us iterate and make a better product for our developers.


Cheers!
Jon

**Comment by davhin** [comment]
We are currently filtering for the deleted template ids which thankfully is not a long operation :) appreciate the detailed answer!
