### ISSUE TITLE
400 HTTP errors with get_events() per specific metric ids

### ISSUE THREAD

**Issue by odedva** [klaviyo/klaviyo-api-python#41]
Hello there,
we started getting 400 errors today from klaviyo API get_events when filtering on specific metric ids.
this is the error:
```
HTTP response body: {"errors":[{"id":"1e7d5dd1-1af1-4599-9ae4-6e5f64bd66d9","status":400,"code":"invalid","title":"Invalid 
input.","detail":"Metric IDs ['SOME_METRIC_ID'] do not exist.","source":{"parameter":"filter"},"meta":{}}]}
```
the thing is that we get `SOME_METRIC_ID` from a previous call to `get_metrics()` call from the api, so this is a legitimate metric as far as i undersatnd.

we saw this with multiple stores we operate, and wonder why is that happening. it is mostly happening for some metric ids that represent metrics like `Viewed Form`, `Closed Form`, `subscribe_page_view` and some more...

wondering what we are missing, as other metric ids that get_metrics works just fine.

**Comment by odedva** [comment]
I saw that you had a big release today, and wondering if it's somehow related... please let us know if it's related in a way,
thanks

**Comment by odedva** [comment]
@jon-batscha are you able to help with that?

**Comment by jon-batscha** [comment]
Hi Oded,

I just ran the following code to try to reproduce the error, but got only success responses:

```python
from klaviyo_api import KlaviyoAPI

klaviyo = KlaviyoAPI("API_KEY")

metrics_response = klaviyo.Metrics.get_metrics()

for metric in metrics_response['data']:
    metric_id = metric['id']
    metric_name = metric['attributes']['name']
    print(metric_id, metric_name)
    
    k_filter = f"equals(metric_id,\"{metric_id}\")"
    events = klaviyo.Events.get_events(filter=k_filter)
    print(len(events['data']))
```

Can you try this and let me know if you still hit an error?

Separately: Can you send me an email to: jonathan.batscha@klaviyo.com? I'd like to connect you to our customer facing engineering team to resolve this issue and any others.

In the meantime, I'll submit a bug ticket to get this looked into.

**Comment by odedva** [comment]
thanks for the response, seems like the issue is now gone. not sure what was the problem but it was definitely not working for some of the metrics.
