### ISSUE TITLE
Pydantic v2 compatibility

### ISSUE THREAD

**Issue by pjmv** [klaviyo/klaviyo-api-python#46]
Hi klaviyo devs :wave:

My app server relies on some features of pydantic only available in v > 2.0, which yields incompatibility issues with the klaviyo client. Is pydantic v2 compatibility anywhere on the roadmap ?

Thanks !

**Comment by Ian-Montgomery-Klaviyo** [comment]
Improving the type support for Python is on the roadmap.

**Comment by AlexJMohr** [comment]
Also blocked by this. I would like to use another package that depends on pydantic > 2

**Comment by davideagle** [comment]
> Improving the type support for Python is on the roadmap.

any idea to when that would be?

**Comment by t16n** [comment]
this is a also an issue for our team

**Comment by matanper** [comment]
also missing pydantic v2
note that you can still use v1 while allowing v2 to be installed:
```python
from pydantic.v1 import BaseModel
```

**Comment by ivanarena** [comment]
any update on this issue?

**Comment by erandagan** [comment]
Same here, really frustrating to rewrite a lot of code to use the REST api directly instead.

**Comment by sanfordj** [comment]
hello! @jasonsbrooks @erandagan @Solarden @ivanarena @matanper @pjmv @t16n @davideagle @AlexJMohr 
we've just released v8.0.0 which has Pydantic V2 compatibility
