### ISSUE TITLE
Get Profiles: Phone Numbers Return In Wrong Format

### ISSUE THREAD

**Issue by brandon-clair** [klaviyo/klaviyo-api-python#48]
When requesting profiles with `KlaviyoAPI().Profiles.get_profiles()`, I'm receiving some that are not in E.164 format. Some come back like "(###) ###-####". Accessing a profile in the console shows that the contact information for such profiles do indeed have them saved in non-standard formats. Shouldn't these values be coerced into E.164 format prior to being sent back in an API response?

**Comment by Ian-Montgomery-Klaviyo** [comment]
While the current API verifies that phone numbers are sent in E.164 format, the older api versions didn't have the same guardrails. This probably means that the differently formatted phone numbers are saved in the database in that format from before the E.164 verification existed.

**Comment by brandon-clair** [comment]
Is there any initiative underway to migrate old records to the new standards?
(Granted, not all records would indeed be able to convert, but a best-effort approach would be helpful!)

**Comment by sanfordj** [comment]
Checking on this, I will update this thread when I have more information.

**Comment by sanfordj** [comment]
Hello again. I spoke with the team responsible for this API and while a migration for this is not currently in the roadmap, they advise you to [contact support](https://help.klaviyo.com/hc/en-us/articles/115001002272) and have them file a bug ticket for this. Please be sure to include the company IDs that you are using our API for, and a link to this Github issue.

This will help the team prioritize this work. Thanks for bringing this to our attention!
