### ISSUE TITLE
Events.create_event doesn't seem to send the value_currency parameter

### ISSUE THREAD

**Issue by nburt** [klaviyo/klaviyo-api-python#49]
Based on the [Create Event docs](https://developers.klaviyo.com/en/reference/create_event) and the [events integration doc](https://developers.klaviyo.com/en/docs/guide_to_integrating_a_platform_without_a_pre_built_klaviyo_integration) it seems like I should be able to pass a value_currency when creating an event. In this case I'm trying to create a "Started Checkout" event.

It seems like that parameter is missing in [this file](https://github.com/klaviyo/klaviyo-api-python/blob/main/src/openapi_client/models/event_create_query_v2_resource_object_attributes.py#L33) so it is left out. We track sales in several countries so it is important for us to be able to track this attribute. Is it possible to add this parameter in?

**Comment by sanfordj** [comment]
hello! this `value_currency` field was added after our most recent API release `2024-02-15`, so we will have to do a point release of the SDK to add this in. we will update this thread when its done!

**Comment by sanfordj** [comment]
Hello! as we are preparing for a new API revision release soon, we've decided to bundle this change in with that release. Sorry for any confusion. That will be the 2024-05-15 API revision. I will update this thread again if anything changes.

**Comment by sanfordj** [comment]
this is in the most recent release: https://github.com/klaviyo/klaviyo-api-python/blob/main/src/openapi_client/models/event_create_query_v2_resource_object_attributes.py#L36

**Comment by sanfordj** [comment]
addressed ^
