### ISSUE TITLE
Flows pagination not possible

### ISSUE THREAD

**Issue by bakobako** [klaviyo/klaviyo-api-python#5]
Based on the API docs, flows should be paginated with offset pagination : https://developers.klaviyo.com/en/reference/get_flows

When fetching the first page we get a link to a new page. You cannot specify the offset/page cursor in the keyword arguments, like with other Klaviyo resources/objects

There is no way to paginate Get Flows with this library based on what I tried

**Comment by jon-batscha** [comment]
Hey Adam! Great catch!


I'm looking at both our SDKs, as well as our docs (which use the same underlying spec as the SDK), and it looks like we are in fact missing the `page[cursor]` / `page_cursor` in both the docs and the SDK.

I'll connect with my team to raise this issue and release a fix as soon as we can.

In the mean time, to help me root-cause the issue, can you try the following:

Make an outright API request using the [flows API Docs](https://developers.klaviyo.com/en/reference/get_flows), and add in an additional `page[cursor]` (using the same pattern provided in our docs with a currently documented `page[cursor]`).

Let me know if you have any luck with that, and likewise, I'll follow up here once I've heard back from my team.

Thanks again for raising this, your feedback is super valuable!


Cheers,
Jon

**Comment by bakobako** [comment]
When adding the additional page[cursor] I get the error:

{"errors":[{"id":"5141e3d7-1cfc-4deb-97fc-3fde014eeaf1","status":400,"code":"invalid","title":"Invalid input.","detail":"'page_cursor' is not a valid field for the resource 'flow'.","source":{"pointer":"/data/attributes/page_cursor"},"meta":{}}]}


code to test:

```
import requests
import json

url = "https://a.klaviyo.com/api/flows/"

headers = {
    "accept": "application/json",
    "revision": "2022-10-17",
    "Authorization": "Klaviyo-API-Key API_KEY"
}

response = requests.get(url, headers=headers)
response_data = json.loads(response.text)
next_link = response_data.get("links").get("next")

cursor_url = f"https://a.klaviyo.com/api/flows/?page[cursor]={next_link}"
cursor_response = requests.get(cursor_url, headers=headers)
print(cursor_response.text)

```

Even the official docs say that there is a offset pagination for the endpoint.
When i just use the link, it works:

```
import requests
import json

url = "https://a.klaviyo.com/api/flows/"

headers = {
    "accept": "application/json",
    "revision": "2022-10-17",
    "Authorization": "Klaviyo-API-Key API_KEY"
}

response = requests.get(url, headers=headers)
response_data = json.loads(response.text)
next_link = response_data.get("links").get("next")

cursor_url = next_link
cursor_response = requests.get(cursor_url, headers=headers)
print(cursor_response.text)
```

So I am hoping this can get integrated in the SDK

**Comment by bakobako** [comment]
@jon-batscha any update on this please?

**Comment by jon-batscha** [comment]
Hey! Thanks for reaching out, good catch! (and a timely one).

We have a fix for this, which we will be releasing within the next day, for our SDKs, as well as related services (docs, postman, etc).

Please, stay in touch and let us know of any further issues you come across. Your feedback is super valuable to us in improving our developer tools.

Cheers!
Jon

**Comment by jon-batscha** [comment]
Following up on this:

I am happy to confirm that the updates we shipped yesterday resolved this issue. You can now page through flows using the same page_cursor interface as our other collection endpoints.

Again: thank you so much for catching this issue and bringing it to our attention. It takes great attention to detail on your part to catch a bug that went unnoticed by many others, and we greatly appreciate you reaching out to make us aware. If you run into any further issues, please do not hesitate to reach out. 

Cheers!
Jon
