### ISSUE TITLE
filter param duplicated in version 8.0.0

### ISSUE THREAD

**Issue by nburt** [klaviyo/klaviyo-api-python#51]
I have been using vcrpy to record API calls and replay them in tests. Since upgrading this library to v8.0.0, get_profiles requests are failing due to a cassette mismatch.

Using get_profiles to filter based on an email now duplicates the filter parameter causing the mismatch.

Query: `klaviyo.Profiles.get_profiles(filter=f'equals(email,"{email}")')`

V7.0.0 would construct a query as: `https://a.klaviyo.com/api/profiles/?filter=equals%28email%2C%22test%2Bnewsubscriber%40gmail.com%22%29`

V8.0.0 now creates: `https://a.klaviyo.com/api/profiles/?filter=equals%28email%2C%22test%2Bnewsubscriber%40gmail.com%22%29&filter=equals%28email%2C%22test%2Bnewsubscriber%40gmail.com%22%29`

I'm not noticing an issue with the results which are returned in V8.0.0, however I do need to regenerate test yml files or ignore the filter query param to get tests passing again.

**Comment by sanfordj** [comment]
Working on a fix for this! I hope to release it tomorrow.

**Comment by sanfordj** [comment]
The fix is in https://github.com/klaviyo/klaviyo-api-python/releases/tag/v8.0.1
