### ISSUE TITLE
Removal of get_or_create profile

### ISSUE THREAD

**Issue by wdifruscio** [klaviyo/klaviyo-api-python#57]
is it possible for you guys to implement this back in?

one of the reasons I use klaviyo is so that I don't have to manage and track who is subscribed to what - with the new changes I now have to either run multiple calls to find out who a user is and what they are subscribed to, rather than just sending an email to an endpoint

also - to be clear, without this get_or_create profile - for me to add someone to a list I need to:

1. run a get query to retrieve all profiles with an associated email
2. write logic to determine if the profile is correct or not
3. if no profile, create a new with required params
4. otherwise request to add to the list with the id returned

**Comment by jason-myers-klaviyo** [comment]
Hi @wdifruscio 

We do have an [upsert profile API](https://github.com/klaviyo/klaviyo-api-python/blob/main/src/openapi_client/api/profiles_api.py#L55) that is a "create or update" with a single call, and returns the profile that was created/updated.  ([Docs](https://developers.klaviyo.com/en/reference/create_or_update_profile))

Is this what you mean?  This API should still be available

**Comment by nburt** [comment]
I'd second that a get_or_create method would be helpful. I ended up implementing my own method which calls `klaviyo.Profiles.get_profiles(filter=f'equals(email,"{email}")')` and if no profile is returned will call `klaviyo.Profiles.create_profile(data)`. Recently, we've had 4 or 5 errors with the method as the get_profiles returns none but the create_profile call throws and ApiException with `A profile already exists with one of these identifiers.`. I'm assuming there is some kind of race condition happening so I'll be rescuing it and retrying the get_profiles call but would be helpful if this was handled within the library itself and I didn't need to implement the custom logic myself.

**Comment by sanfordj** [comment]
@nburt sorry for the delay in reply. would the `create_or_update` as @jason-myers-klaviyo  method not work for you in this scenario?

**Comment by wdifruscio** [comment]
Hi all,

sorry  - I've been meaning to reply here

Yes I did implement this, but I found the entire migration to this new system to be pretty irritating, and the documentation to be sub-par.  It is a considerable cost to run these services, if this was open source I would be more forgiving and probably would not be publicly whining

I totally get why things were moved into the system that they are now - it is standardized and basically follows a known convention - which in theory is very nice - but documentation and path to upgrade could have been well thought out - the emails to upgrade were nice, but actual information was not great

This change cost a considerable amount of hours, which really should have been done within an afternoon, as the original implementation was, so I am bit dissapointed in everything. I use this sdk with several companies and had to painfully line by line the new arduous implemention with multiple developers who were equally annoyed and confused

**Comment by nburt** [comment]
@sanfordj our use case has been that we're trying to find or create a profile prior to sending events for them (viewed product, started checkout, placed order) so that we can send the profile ID along with the event. I suppose we could do a create_or_update with empty values but we aren't actually updating the profile so I think that a find or create API would be more appropriate.

**Comment by cpcurtis1218** [comment]
We appreciate your feedback, and apologize for any frustration you experienced here. We're always trying to improve our SDK documentation.

@wdifruscio, for your use case, we'd recommend using `create_or_update_profile`
for the relevant identifier (e.g. email address). This will create a new profile if one doesn't exist, or return the profile if it already exists. Then you can add that profile to a list via `create_list_relationships`.

@nburt, for your use case, we'd recommend one of the following options, with (1) being the simpler route:
1) Call create_event with the relevant  profile identifier (e.g. the `email`). Profile ID is an optional field; it is not required. This will create the profile if one doesn't exist already or find the relevant profile prior to creating the event.
2)Use `create_or_update_profile` for the provided email address. This will create the profile if one doesn't exist; if not it will return a profile that already has that . Then you can call the create event endpoint using the profile ID.
