### ISSUE TITLE
Klaviyo profile unable to subscribe: due to HTTPSConnectionPool

### ISSUE THREAD

**Issue by iamalisajid** [klaviyo/klaviyo-api-python#7]
Klaviyo throws exceptions sometime on local machine:

``` Klaviyo profile unable to subscribe: due to HTTPSConnectionPool(host='a.klaviyo.com', port=443): Max retries exceeded with url: /api/profile-subscription-bulk-create-jobs/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))) ```

**Comment by dano-klaviyo** [comment]
@iamalisajid Are you still experiencing the same issue? Do you get the same error when you run this on something like aws or gcp?

**Comment by iamalisajid** [comment]
I actually fixed it by creating the new connection every time
