### ISSUE TITLE
Long import time

### ISSUE THREAD

**Issue by AlexJMohr** [klaviyo/klaviyo-api-python#73]
Importing the klaviyo_api module takes a very long time (up to 2 seconds) even on a fast NVME SSD. See the attached [log file](https://github.com/user-attachments/files/17639212/klaviyo.log), generated from `python -X importtime -c 'import klaviyo_api'`.

Here is a visualization using [tuna](https://github.com/nschloe/tuna):
![image](https://github.com/user-attachments/assets/bd19a720-7549-42ae-b481-feb4e70c17cb)

The long import time is very inconvenient while iterating in development.

If the package were to be restructured such that the top-level `klaviyo_api` module doesn't import everything in `openapi_client`, import would be much faster.

**Comment by dsmcfarl** [comment]
I can confirm this issue. I experience about 5 second load time. If I have PYTHONTRACEMALLOC=1 env variable set, it takes 26 seconds. 

![image](https://github.com/user-attachments/assets/542e43f7-1fe0-430d-b154-6acc509edb84)

with PYTHONTRACEMALLOC=1
![image](https://github.com/user-attachments/assets/e6435dee-6c07-415e-9104-c3047a7429e5)

**Comment by vpylypenko-klaviyo** [comment]
Thank you for reaching out and bringing this to our attention. We’re investigating the issue and will update you as soon as we have more information.

**Comment by ben-horgan-klaviyo** [comment]
In v15.0.0 we've added optional lazy importing which should significantly decrease import time (see [README](https://github.com/klaviyo/klaviyo-api-python?tab=readme-ov-file#lazy-imports)). Set the `KLAVIYO_PYTHON_SDK_LAZY_IMPORTS` env variable to `true` to enable this.
