### ISSUE TITLE
Pydantic Version Break

### ISSUE THREAD

**Issue by jdephil** [klaviyo/klaviyo-api-python#74]
I installed klaviyo today which installed pydantic as a dependency. It looks like their package is currently installing beta version 2.10.0b1 as their newest default and just importing klaviyo into my views.py file caused a breaking error. I installed pydantic manually and pinned it to 2.9.* which fixed the issue.

`ImportError: cannot import name 'VALIDATE_CALL_SUPPORTED_TYPES' from partially initialized module 'pydantic._internal._validate_call' (most likely due to a circular import)`

`pydantic version: 2.10.0b1
        pydantic-core version: 2.26.0
          pydantic-core build: profile=release pgo=false
                 install path: /Users/jpdephillips/.local/share/virtualenvs/iconic-DQE3a5P9/lib/python3.10/site-packages/pydantic
               python version: 3.10.0 (default, Mar  8 2024, 14:47:28) [Clang 14.0.0 (clang-1400.0.29.102)]
                     platform: macOS-14.1-x86_64-i386-64bit
             related packages: typing_extensions-4.12.2
                       commit: unknown`

**Comment by ben-horgan-klaviyo** [comment]
Thanks for bringing this up - it should be installing 2.9.2, the latest stable version of Pydantic, as pip does not install pre-release versions by default (see [here](https://pip.pypa.io/en/stable/cli/pip_install/#pre-release-versions)). How are you installing the Klaviyo SDK?

**Comment by jdephil** [comment]
I ran `pipenv install klaviyo-api`. When I manually installed pydantic before pinning it, it also installed as 2.10.0b1.

**Comment by ben-horgan-klaviyo** [comment]
Thanks- unfortunately I cannot reproduce this and don't know how a prerelease version would be installed without the `--pre` flag or setting `allow_prereleases` in a `Pipfile`. But when I use `--pre`, I can reproduce the error you got.

Thank you for raising this with Pydantic, I'll follow the [issue](https://github.com/pydantic/pydantic/issues/10799).

**Comment by jdephil** [comment]
All good if you aren't able to reproduce since I was able to resolve regardless. Happy to close this out!
